# Generated by Django 2.1.7 on 2019-03-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/images/teammembers')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=128)),
            ],
        ),
    ]
