# Generated by Django 3.0.5 on 2020-05-10 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teamMembers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='only png, jpg, jpeg extensions')], verbose_name='Image')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
