# Generated by Django 2.1.7 on 2019-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190315_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image_height',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_width',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
