# Generated by Django 3.0.5 on 2020-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200424_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=64), max_length=64, unique=True, verbose_name='URL'),
        ),
    ]
