# Generated by Django 3.0.5 on 2020-04-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='URL'),
        ),
    ]
