# Generated by Django 3.0.5 on 2020-04-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20200427_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
    ]
