# Generated by Django 3.0.5 on 2020-04-26 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_remove_teammember_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
