# Generated by Django 3.0.5 on 2020-04-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
