# Generated by Django 3.0.5 on 2020-05-27 19:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(default='', upload_to='category', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])])),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирма',
            },
        ),
        migrations.CreateModel(
            name='ModelSizeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ключ на размеры для модели',
                'verbose_name_plural': 'Ключ на размеры для модели',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='', max_length=64)),
                ('foo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Стать',
                'verbose_name_plural': 'Стать',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])])),
                ('name', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('price', models.CharField(default='0$', max_length=64)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField()),
                ('sale_cnt', models.PositiveIntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='added date')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainShop.Category')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модель',
            },
        ),
        migrations.CreateModel(
            name='ShoesGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainShop.Shoes')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='ShoesSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_size', models.CharField(default='36', max_length=2)),
                ('shoes_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainShop.ModelSizeList')),
            ],
            options={
                'verbose_name': 'Доступные размеры',
                'verbose_name_plural': 'Доступные размеры',
            },
        ),
        migrations.CreateModel(
            name='ShoesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='shoes_detail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])])),
                ('shoes_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainShop.ShoesGallery')),
            ],
            options={
                'verbose_name': 'Фото обуви',
                'verbose_name_plural': 'Фото обуви',
            },
        ),
        migrations.AddField(
            model_name='modelsizelist',
            name='shoes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainShop.Shoes'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_for_sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainShop.Sex'),
        ),
    ]
