# Generated by Django 3.0.5 on 2020-05-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSizeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainShop.Shoes')),
            ],
            options={
                'verbose_name': 'ModelSizeList',
                'verbose_name_plural': 'ModelSizeList',
            },
        ),
        migrations.CreateModel(
            name='ShoesSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_size', models.CharField(default='36', max_length=2)),
                ('shoes_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainShop.ModelSizeList')),
            ],
            options={
                'verbose_name': 'ShoesSize',
                'verbose_name_plural': 'ShoesSize',
            },
        ),
    ]
