# Generated by Django 3.0.5 on 2020-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '43'), ('44', '44'), ('45', '45'), ('46', '46')], default='0', max_length=2),
        ),
    ]
