# Generated by Django 3.0.5 on 2020-05-27 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_for_sex',
        ),
        migrations.AddField(
            model_name='category',
            name='sex',
            field=models.CharField(default='unisex', max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(upload_to='shoes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='shoesimage',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='shoes_detail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
    ]
