# Generated by Django 3.0.5 on 2020-05-29 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0002_auto_20200527_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='size_table', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])])),
            ],
            options={
                'verbose_name': 'Таблица размеров',
                'verbose_name_plural': 'Таблицы размеров',
            },
        ),
    ]
