# Generated by Django 2.1.3 on 2019-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0002_auto_20190314_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='sale_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(upload_to='shoes'),
        ),
    ]
