# Generated by Django 2.1.3 on 2019-05-07 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0003_auto_20190503_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='sale_cnt',
        ),
        migrations.AddField(
            model_name='shoes',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 6, 57, 17, 599167, tzinfo=utc), verbose_name='added date'),
        ),
    ]
