# Generated by Django 3.0.5 on 2020-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0004_auto_20200529_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoes',
            name='price_after_discount',
            field=models.CharField(blank=True, default='0$', max_length=64),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.CharField(default='1$', max_length=64),
        ),
    ]
