# Generated by Django 3.0.5 on 2020-04-21 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0005_auto_20190508_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 14, 38, 40, 161888, tzinfo=utc), verbose_name='added date'),
        ),
    ]
