# Generated by Django 3.0.5 on 2020-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0006_auto_20200602_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '.Бренд', 'verbose_name_plural': '.Бренды'},
        ),
        migrations.AlterModelOptions(
            name='modelsizelist',
            options={'verbose_name': '.Размеры', 'verbose_name_plural': '.Размеры'},
        ),
        migrations.AlterModelOptions(
            name='shoesgallery',
            options={'verbose_name': '.Галерея', 'verbose_name_plural': '.Галереи'},
        ),
        migrations.AlterModelOptions(
            name='shoessize',
            options={'verbose_name': 'Список размеров', 'verbose_name_plural': 'Список размеров'},
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.CharField(default='1 грн.', max_length=64),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price_after_discount',
            field=models.CharField(blank=True, default='0 грн.', max_length=64),
        ),
        migrations.AlterField(
            model_name='shoessize',
            name='model_size',
            field=models.CharField(default='', max_length=2),
        ),
    ]
