# Generated by Django 3.0.5 on 2020-04-24 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0006_auto_20200421_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='added date'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(upload_to='shoes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
