# Generated by Django 3.0.5 on 2020-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0007_auto_20200424_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
