# Generated by Django 3.0.5 on 2020-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0007_auto_20200603_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoesimage',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='shoessize',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размер'},
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.FloatField(default='1'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price_after_discount',
            field=models.FloatField(blank=True, default='0'),
        ),
    ]
