# Generated by Django 3.0.5 on 2020-06-25 14:01

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0008_auto_20200603_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.FloatField(default='1.0'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price_after_discount',
            field=models.FloatField(blank=True, default='0.0'),
        ),
    ]
