# Generated by Django 3.0.5 on 2020-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0010_auto_20200625_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': '.Модель', 'verbose_name_plural': '.Модель'},
        ),
        migrations.AlterField(
            model_name='shoes',
            name='name',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
