# Generated by Django 3.0.5 on 2020-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=64), max_length=64, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=128), max_length=128, unique=True, verbose_name='URL'),
        ),
    ]
