# Generated by Django 3.0.5 on 2020-04-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0012_auto_20200427_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='URL'),
        ),
    ]
