# Generated by Django 3.0.5 on 2020-04-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0013_auto_20200427_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='slug',
        ),
    ]
