# Generated by Django 3.0.5 on 2020-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0014_auto_20200625_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='name',
        ),
        migrations.AlterField(
            model_name='shoessize',
            name='model_size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
