# Generated by Django 3.0.5 on 2020-04-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0015_auto_20200427_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
