# Generated by Django 3.0.5 on 2020-04-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0016_auto_20200427_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='price',
            field=models.CharField(default='0$', max_length=64),
        ),
    ]
