# Generated by Django 3.0.5 on 2020-04-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0017_shoes_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=64)),
                ('surname', models.CharField(default='Surname', max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('mod_check', models.BooleanField(default=False)),
            ],
        ),
    ]
