# Generated by Django 3.0.5 on 2020-04-30 22:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0018_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='address',
            field=models.CharField(default='Address', max_length=128),
        ),
        migrations.AddField(
            model_name='userorder',
            name='email',
            field=models.EmailField(default='defaultemail@django.com', max_length=128),
        ),
        migrations.AddField(
            model_name='userorder',
            name='phone_no',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='shoes_name',
            field=models.CharField(default='Shoes name', max_length=64),
        ),
        migrations.AddField(
            model_name='userorder',
            name='size',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='userorder',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='order time'),
        ),
    ]
