# Generated by Django 3.0.5 on 2020-05-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0019_auto_20200501_0150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
